name: CI

on:
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: PowerShell

jobs:
  AnalyzeTests:
    runs-on: [ windows-latest ]
    outputs:
      tests: ${{ steps.Analyze.outputs.tests }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Analyze
        id: Analyze
        run: |
          $tests = @(Get-ChildItem -Path (Join-Path $ENV:GITHUB_WORKSPACE 'Tests\*.ps1') -Exclude @("_*.ps1") | ForEach-Object { $_.BaseName }) | ConvertTo-Json -compress
          Write-Host "::set-output name=tests::$tests"
          Write-Host "set-output name=tests::$tests"

  RunTests:
    runs-on: [ windows-latest ]
    needs: [ AnalyzeTests ]
    strategy:
      matrix:
        test: ${{fromJson(needs.AnalyzeTests.outputs.tests)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Tests - AppHandling (NAV)
        run: |
          . .\Tests\_TestRunOne.ps1 -licenseFile '${{ secrets.licensefile }}' -buildLicenseFile '${{ secrets.buildLicenseFile }}' -insiderSasToken '${{ secrets.insiderSasToken }}' -testScript '${{ matrix.test }}.ps1'

