name: Release

on:
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: PowerShell

jobs:
  Deploy:
    runs-on: [ windows-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Tests
        run: |
          $path = $ENV:GITHUB_WORKSPACE
          $tempPath = Join-Path $ENV:TEMP ([GUID]::NewGuid().ToString())
          New-Item -Path $tempPath -ItemType Directory | Out-Null
          Copy-Item -Path $path -Destination $tempPath -Recurse
          
          Remove-Item -Path (Join-Path $path "Tests") -Force -Recurse
          Remove-Item -Path (Join-Path $path ".gitignore") -Force
          Remove-Item -Path (Join-Path $path "README.md") -Force

          $versionFile = Join-Path $path 'Version.txt'
          $version = (Get-Content -Path $versionFile).split('-')[0]
          Write-Host "BcContainerHelper version $Version"
          Set-Content -Path $versionFile -Value $version

          $modulePath = Join-Path $tempPath "NavContainerHelper\BcContainerHelper.psm1"
          Import-Module $modulePath -DisableNameChecking

          $functionsToExport = (get-module -Name BcContainerHelper).ExportedFunctions.Keys | Sort-Object
          $aliasesToExport = (get-module -Name BcContainerHelper).ExportedAliases.Keys | Sort-Object

          $releaseNotes = Get-Content -Path (Join-Path $path "ReleaseNotes.txt")
          $idx = $releaseNotes.IndexOf($version)
          if ($idx -lt 0) {
              throw 'No release notes identified'
          }
          $versionReleaseNotes = @()
          while ($releaseNotes[$idx]) {
              $versionReleaseNotes += $releaseNotes[$idx]
              $idx++
          }

          Write-Host "Release Notes:"
          Write-Host $VersionReleaseNotes

          Write-Host "Update Module Manifest"
          Update-ModuleManifest -Path (Join-Path $path "BcContainerHelper.psd1") `
                                -RootModule "BcContainerHelper.psm1" `
                                -ModuleVersion $version `
                                -Author "Freddy Kristiansen" `
                                -FunctionsToExport $functionsToExport `
                                -AliasesToExport $aliasesToExport `
                                -CompanyName "Microsoft" `
                                -ReleaseNotes $versionReleaseNotes

          Write-Host "Upload to storage (preview)"
          $storageContext = New-AzStorageContext -ConnectionString '${{ secrets.BchStorageConnectionString }}'
          New-AzStorageContainer -Name 'test' -Context $storageContext -Permission 'Container' -ErrorAction Ignore | Out-Null

          Compress-Archive -path $path -DestinationPath "$($path).zip"
          Set-AzStorageBlobContent -File "$($path).zip" -Context $storageContext -Container 'public' -Blob "$version.zip" -Force | Out-Null
          Set-AzStorageBlobContent -File "$($path).zip" -Context $storageContext -Container 'public' -Blob "latest.zip" -Force | Out-Null

          #Write-Host "Publishing Module"
          #Publish-Module -Path $path -NuGetApiKey '@{{ secrets.NugetKey }}' -SkipAutomaticTags
